### ISSUE TITLE
The extension crashes on .md files with emoji characters

### ISSUE THREAD

**Issue by GiscardBiamby** [quilicicf/vscode-markdown-spec-formatter#19]
Example characters:

❤️✨🦄

If these are in a markdown file, vscode cannot format the document with this extension. You get an error that says "Extension host terminated unexpectedly. And you get an option to "Open Developer Tools" or to "Restart Extension Host".

**Comment by quilicicf** [comment]
Dang, didn't have notifications on for this repo, this completely flew below my radar :sweat_smile: 

In the unlikely event that you are still interested in the plugin, it works on my machine so it's either been fixed since reported or I'll need more info about your setup.

Works for me on:
* Ubuntu `22.04`
* VSCode `1.77.3`
* Extension `1.1.2`

I added the characters ❤️✨🦄 to the README as a cheap regression test.
